# Enable validating this file
version: ~> 1.0

language: python
python:
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR
